# Generated by Django 5.2.5 on 2025-08-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('absent_teacher', models.CharField(max_length=255)),
                ('replacement_teacher', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(db_column='class', max_length=255)),
                ('period', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'arrangements',
            },
        ),
        migrations.CreateModel(
            name='CoverageTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
                ('class_name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('original_teacher_id', models.CharField(max_length=255)),
                ('replacement_teacher_id', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'coverage_tracking',
            },
        ),
        migrations.CreateModel(
            name='SchoolLogic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logic_name', models.CharField(max_length=255)),
                ('logic_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'school_logic',
                'unique_together': {('school', 'logic_name')},
            },
        ),
        migrations.CreateModel(
            name='SuspendedDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'suspended_dates',
                'unique_together': {('school', 'date')},
            },
        ),
    ]
