# Generated by Django 5.2.5 on 2025-08-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('period_number', models.IntegerField()),
                ('class_info', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'daily_schedules',
            },
        ),
        migrations.CreateModel(
            name='SchedulesSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('period1', models.CharField(blank=True, max_length=255, null=True)),
                ('period2', models.CharField(blank=True, max_length=255, null=True)),
                ('period3', models.CharField(blank=True, max_length=255, null=True)),
                ('period4', models.CharField(blank=True, max_length=255, null=True)),
                ('period5', models.CharField(blank=True, max_length=255, null=True)),
                ('period6', models.CharField(blank=True, max_length=255, null=True)),
                ('period7', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'schedules_summary',
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('substitute_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject_expertise', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(default='Available', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'substitutes',
                'unique_together': {('school', 'substitute_id')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('biometric_code', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('school', 'teacher_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkloadCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=255)),
                ('workload_count', models.IntegerField(default=0)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'workload_counter',
                'unique_together': {('school', 'teacher_id')},
            },
        ),
    ]
