# Generated by Django 5.2.5 on 2025-08-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('timing_id', models.AutoField(primary_key=True, serialize=False)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'timing',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('teacher_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('is_auto', models.BooleanField(default=False)),
                ('biometric_code', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.school')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('school', 'date', 'teacher_id')},
            },
        ),
    ]
